### ISSUE TITLE
update modules to 1.0.1

### ISSUE THREAD

**Issue by derhuerst** [public-transport/friendly-public-transport-format#10]
For a standard, it is very im important to have specific versions when referring to it. Right now, in npm packages, we just vaguely link to the whole FPTF repo.

**I'd suggest to use [SemVer](http://semver.org) for this format/standard.** Which would mean that, whenever we make changes that would break FPTF-exposing or FPTF-consuming libs, we increase the major version.

**We can use [Git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging)** to mark versions permanently. This is great for technical accessibility (such as using this repo as a dependency), but for greater *human* accessibility (or visibility if you will), **we may also want to use GitHub releases or even publish to npm**. Publishing to npm would become especially useful if we added valid and invalid examples of FPTF data to test libraries against.

I started a new project [`validate-fptf`](https://github.com/derhuerst/validate-fptf#validate-fptf) to validate data against the format using JS. I think it makes sense to let this tool's versions follow the FPTF versions.

Decisions to make:

- [x] use SemVer?
- [x] GitHub releases?
- [x] npm releases?

Things to do:

- [x] add valid/invalid examples – #12
- [x] close all outstanding issues for [this milestone](https://github.com/public-transport/friendly-public-transport-format/milestone/1)

Follow-up after creating a release:

- [x] change links in libs to a specific version
- [x] adapt `validate-fptf`.
- [x] write a `contributing.md` with a reminder to update `validate-fptf` according to FPTF changes – #14
- [x] put a [code of conduct](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/) in place, e.g. [the Contributor Covenant](https://www.contributor-covenant.org)?

**Comment by juliuste** [comment]
👍 for SemVer!

**Comment by derhuerst** [comment]
BTW I'd propose `1.0.0` as a first release. Below `1.0.0`, according to SemVer, every minor version bump is considered breaking. I think that, from the beginning, we should start with a version number that supports non-breaking updates.

**Comment by kiliankoe** [comment]
Afaik SemVer basically says anything goes for <1.0.0.

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Which might be helpful to get stuff to a polished point. Otherwise possible mode renames and whatnot could lead to fptf being available in several "initial" releases, which might end up being confusing for people looking to implement it.

**Comment by derhuerst** [comment]
> Afaik SemVer basically says anything goes for <1.0.0. [...] Which might be helpful to get stuff to a polished point.

Fair enough.

> Otherwise possible mode renames and whatnot could lead to fptf being available in several "initial" releases, which might end up being confusing for people looking to implement it.

I don't get it. Several releases as in `1.0.0`, `2.0.0`, ...?

**Comment by kiliankoe** [comment]
Yeah, several major version bumps. I'm probably one of those people that get to emotionally attached to a version identifier, so please disregard my opinion on this, but I have the feeling that it might be odd for FPTF to be available in version 1.0.0-5.0.0 or so because of tiny breaking changes that force strict major bumps before many people come around to using it. 

But yeah, I don't want to get into the way of anything and would still definitely prefer using semver over anything else. And definitely 👍 for using GitHub releases.

**Comment by derhuerst** [comment]
We can keep using SemVer and make you feel comfortable about the version numbers at the same time. Eventually we'll need to adapt all FTPF-dependent projects anyways, regardless of wether the last/second version is called `1.0.0` or `2.0.0`.

**Comment by derhuerst** [comment]
AFAICT, all of these links should be updated to point to the `1.0.1` version of FPTF specifically:

- [ ] https://github.com/kiliankoe/FPTF.swift/blob/035adcdb29e0445f383d2054ba2df361fb10e67c/README.md#L3
- [ ] https://github.com/derhuerst/ecolines/blob/1a39b94ca36855c1f6109119e730e62c40836659/readme.md#L12
- [ ] https://github.com/juliuste/meinfernbus/blob/1c7318ef2ea8775ac96d1ac6ced8219920b7cb40/docs/regions.md#L4
- [ ] https://github.com/juliuste/deinbus/blob/1e22932ccff12bceb4073f6ccbcfce2c952ccbf6/readme.md#L3
- [ ] https://github.com/juliuste/interrail/blob/b08ae2f879fa9bafea4e325587257830b7fa3d8d/readme.md#L3
- [ ] https://github.com/juliuste/interrail/blob/b08ae2f879fa9bafea4e325587257830b7fa3d8d/readme.md#L24
- [ ] https://github.com/juliuste/slovenske-zeleznice/blob/cf89f770428a6b0b1f9e28428440cb035c94ae73/docs/stations.md#L3
- [ ] https://github.com/juliuste/mav/blob/fb412e75f28ddd7b910a45d2a55ed5d2bd73619f/docs/stations.md#L3
- [ ] https://github.com/juliuste/comboios/blob/e2b0664513cfad262de9c01015511f5a7c9268f2/docs/stations.md#L3
- [ ] https://github.com/juliuste/eurolines-de/blob/d38ef1180e731b7fefb6180ef9eb0d0adbe42a27/readme.md#L3
- [ ] https://github.com/derhuerst/vbb-mode-weights/blob/31b48cf7c87cb8dcf22293578efe8f552d84f6dd/readme.md#L19
- [ ] https://github.com/juliuste/meinfernbus/blob/5b3ab2d1d0ae3fd65ce0c40c238e774872e340bf/readme.md#L24
- [ ] https://github.com/derhuerst/vbb-trips/blob/7273f05c35b8e9b7c62b3d8e89a127bea6eadcc1/readme.md#L33
- [ ] https://github.com/juliuste/meinfernbus/blob/3f2c8ce7c6ccea3931e1c60172683e5fea4722c7/docs/stations.md#L3
- [ ] https://github.com/juliuste/oebb/blob/6211f09e1b5ece8be06a9a8cd2a09264688600d4/readme.md#L23
- [ ] https://github.com/derhuerst/locomore/blob/1edc9eeb1a72f04fd4dcc23b0cdb051b985f58f9/readme.md#L12
- [ ] https://github.com/derhuerst/locomore/blob/1edc9eeb1a72f04fd4dcc23b0cdb051b985f58f9/readme.md#L28
- [ ] https://github.com/juliuste/lvb/blob/6053497f83ce647fdecf21b0cea5defeb2bbe0c8/readme.md#L21
- [ ] https://github.com/juliuste/lvb/blob/6053497f83ce647fdecf21b0cea5defeb2bbe0c8/readme.md#L37
- [ ] https://github.com/juliuste/sncf/blob/87d5ea4e652bc1e48ddd23cb3165e92539b3ffd5/readme.md#L3
- [ ] https://github.com/juliuste/sncf/blob/87d5ea4e652bc1e48ddd23cb3165e92539b3ffd5/readme.md#L20
- [ ] https://github.com/derhuerst/discover-vbb-stations/blob/da982b10a6cfb42a31ae5157a7fb9f00385bb8f9/readme.md#L44
- [ ] https://github.com/derhuerst/discover-vbb-stations/blob/da982b10a6cfb42a31ae5157a7fb9f00385bb8f9/readme.md#L45
- [ ] https://github.com/juliuste/tallink/blob/93dac6a8b4558c1c18814ae39404190f88adce8b/readme.md#L3
- [ ] https://github.com/juliuste/tallink/blob/93dac6a8b4558c1c18814ae39404190f88adce8b/readme.md#L23
- [ ] https://github.com/derhuerst/nettbuss-stations/blob/aa155f936785ea3616dd1d4094984c4ec14f2e6b/readme.md#L20
- [ ] https://github.com/juliuste/slovenske-zeleznice/blob/cf89f770428a6b0b1f9e28428440cb035c94ae73/docs/journeys.md#L3
- [ ] https://github.com/juliuste/slovenske-zeleznice/blob/83ad25fb9383ab783e5d4e6e09ef372e47f60310/readme.md#L21
- [ ] https://github.com/derhuerst/vbb-lines-at/blob/6ca31aa1be99a7fc457ebaa228729dfde91176ab/readme.md#L26
- [ ] https://github.com/juliuste/mav/blob/fb412e75f28ddd7b910a45d2a55ed5d2bd73619f/readme.md#L21
- [ ] https://github.com/juliuste/comboios/blob/a733c1026e2444cdd3e7fcc984645133b0d28e86/readme.md#L21
- [ ] https://github.com/public-transport/vbb-sort-lines/blob/80b34b688f0e6d3bd3973e1722da7de09a39323a/readme.md#L20
- [ ] https://github.com/derhuerst/discover-db-stations/blob/a61c4e61d9f007b35b77e3b4349115d569f7abc0/readme.md#L52
- [ ] https://github.com/derhuerst/discover-db-stations/blob/a61c4e61d9f007b35b77e3b4349115d569f7abc0/readme.md#L53
- [ ] https://github.com/derhuerst/vbb-stations-autocomplete/blob/7b357d24af39a0b73c491c5e8fc4c8db83a24939/readme.md#L29
- [ ] https://github.com/derhuerst/vbb-journey-ui/blob/891a68fb0c96242ecb888fea4e932319590ab6d4/readme.md#L43
- [ ] https://github.com/derhuerst/vbb-find-stations/blob/0f39eeab9b6dbf87cef3c347083bdb33886adf50/readme.md#L33
- [ ] https://github.com/derhuerst/db-zugradar-client/blob/f1419d4966bc5e0fcfc0a46b24ed6b1b3a8024cb/readme.md#L53
- [ ] https://github.com/derhuerst/vbb-lines/blob/52a7a204efcbf85c7f446e0cc081b949299066ea/README.md#L20
- [ ] https://github.com/derhuerst/db-zugradar-client/blob/f1419d4966bc5e0fcfc0a46b24ed6b1b3a8024cb/readme.md#L53
- [ ] https://github.com/juliuste/mav/blob/fb412e75f28ddd7b910a45d2a55ed5d2bd73619f/docs/journeys.md#L3
- [ ] https://github.com/derhuerst/vbb-lines/blob/52a7a204efcbf85c7f446e0cc081b949299066ea/README.md#L20
- [ ] https://github.com/derhuerst/db-stations/blob/d401d5aa88b100f9a5ad4e25ee1568d45bad28ac/readme.md#L22
- [ ] https://github.com/derhuerst/db-stations/blob/d401d5aa88b100f9a5ad4e25ee1568d45bad28ac/readme.md#L57
- [ ] https://github.com/juliuste/db-prices/blob/3bc97ed0f37845e84af505fc5ee5a5a6ead734f0/parse.js#L30
- [ ] https://github.com/juliuste/comboios/blob/e2b0664513cfad262de9c01015511f5a7c9268f2/docs/journeys.md#L3
- [ ] https://github.com/derhuerst/db-stations-autocomplete/blob/3b6ccd05d979cdcc02f5facd9f9cc13ea098974f/readme.md#L30
- [ ] https://github.com/derhuerst/flightradar24-client/blob/f39d9956c5cf6b7ea03f2ac51943ffa25333544e/readme.md#L69
- [ ] https://github.com/public-transport/gtfs-to-fptf/blob/9f207957979653f2a212aa2597c9e19330f8eb89/readme.md#L3
- [ ] https://github.com/derhuerst/vbb-stations/blob/c25d377160a4c2cfe9a1f84683b1bf82f30c647b/readme.md#L20
- [ ] https://github.com/derhuerst/vbb-rest/blob/4332462b8a78092c8ec60388888d2a2793d86c6d/docs/index.md#L3
- [ ] https://github.com/derhuerst/vbb-rest/blob/4332462b8a78092c8ec60388888d2a2793d86c6d/docs/index.md#L109
- [ ] https://github.com/juliuste/meinfernbus/blob/b85582d4e4a29544779e1cc173dbf4f991aab265/docs/journeys.md#L3
- [ ] https://github.com/derhuerst/hafas-departures-in-direction/blob/49693c0e13ba9d0f8e34c8cdf532b2742d86b942/readme.md#L49
- [ ] https://github.com/derhuerst/wifi-on-ice-portal-client/blob/48a00a73124ef32ed786130b973f0cd8ad3e30f6/readme.md#L51
- [ ] https://github.com/juliuste/db-prices/blob/3bb79c5f983fc41ac883e27b9deb0f6d9ba1d51e/readme.md#L50
- [ ] https://github.com/derhuerst/vbb-hafas/blob/2f5232c69aea355d9603ef5cec792e432dacfa81/README.md#L41
- [ ] https://github.com/derhuerst/db-hafas/blob/709767133e4d7f760c17bd8ee5bcc6aa92b1bc3a/readme.md#L39
- [ ] https://github.com/public-transport/european-transport-operators/blob/c4738f70644f74c4369266bf1c3dbeb186067024/readme.md#L3

**Comment by juliuste** [comment]
#36

**Comment by juliuste** [comment]
Reminder: Update to `1.1.1`.

**Comment by derhuerst** [comment]
Closing this, as the scope of this Issue is a bit too wide. By now, we have FPTF 1.2.1, and many of the mentioned libs are either updated already or obsolete.
