### ISSUE TITLE
Rename `coordinates` field to `coordinate`

### ISSUE THREAD

**Issue by kiliankoe** [public-transport/friendly-public-transport-format#15]
Small change, but makes more sense imo though if there's just a single pair of lat/lng values. Reading the plural makes me think of getting several value pairs.

Regarding `station` and `stop` objects.

**Comment by juliuste** [comment]
As far as I know, one does always use the term `coordinates` in plural form, because one `coordinate` (singular) would only describe the value for one dimension, e.g. only `latitude` or only `longitude`. Since *both* dimensions are included, the plural form should be correct. But I wouldn't mind being proven wrong here 😄

@derhuerst @dirkschumacher Any opinions?

**Comment by kiliankoe** [comment]
No you're definitely right^^ I've just typically seen a single value pair (or triple if all dimensions are relevant) almost always being referred to as a coordinate, which feels more natural as there's no difference to the plural otherwise. 
Many frameworks (like Apple's CoreLocation) also refer to coordinate objects in the singular to make the distinction clearer.

I just thought that whilst technically being incorrect or at least not entirely correct, it feels more friendly and accessible to change that around^^ It is just a tiny change though, I'm fine with either way.

**Comment by derhuerst** [comment]
@kiliankoe I can see your point. While `coordinates` is technically accurate, it might sounds to people as if we are talking about a *set* of *tuples*.

**Comment by juliuste** [comment]
If it doesn't bother you too much, I'd strongly prefer the plural form since - for me - it seems more intiutive for people not influenced by the naming mistakes* made in other frameworks (including me) 😄 

\* 😛

**Comment by derhuerst** [comment]
Can we close this in favour of #19, as we seem to agree that a `location` object is necessary?

**Comment by juliuste** [comment]
This is still open depending on our decision in #19
