### ISSUE TITLE
Possibly rename `stop` to `platform`?

### ISSUE THREAD

**Issue by kiliankoe** [public-transport/friendly-public-transport-format#16]
I've typically seen what's described here as a `stop` referred to as a platform and `station` as a stop. This is just a basis for discussion though.

**Comment by juliuste** [comment]
We had the problem of naming things smaller than a `station` like *Berlin Hbf* but larger than the actual `platform` *Berlin Hbf, platform 12*. Like the Tram or U-Bahn (metro) part of a station which is often separated from the long-distance train area, for example. Thats why we came up with
`station` *Berlin Hbf* -> `stop` *Berlin Hbf (Tram)* -> `departurePlatform` or `arrivalPlatform` *9¾*

Is there any other term for the thing we call `stop`?

**Comment by derhuerst** [comment]
Yeah, we tried to figure out a tradeoff between

- semantic & intuitive naming
- compatibility with GTFS
- not too strict definitions, to allow for complex examples such as *Berlin Hbf*, *Berlin Hbf tief* and *Berlin Hbf tief Gleis 8*.

**Comment by juliuste** [comment]
Reopen if you have any other suggestion on how we should name the `stop` part. 🙂
