### ISSUE TITLE
indicating fptf version in js modules

### ISSUE THREAD

**Issue by juliuste** [public-transport/friendly-public-transport-format#32]
@derhuerst and I were just briefly discussing on how to indicate the "supported" version of FPTF in JavaScript public transport libraries.

We thought of three different options, but feel free to share any other ideas:

1. Require the `fptf` module (at a specific version) in the `devDependencies`.
2. Require the `validate-fptf` module (at a specific version) in the `devDependencies`.
3. Add a custom `fptf` key to the package.json file, which indicates the version (similar to the `browserify` key)

**Comment by juliuste** [comment]
2. Doesn't seem perfect to me, since there could be bugfixes in `validate-fptf` which would probably result in a disparity between `fptf` and `validate-fptf` versions.

**Comment by juliuste** [comment]
@derhuerst Opinions?

**Comment by juliuste** [comment]
To encourage people to test their modules using `validate-fptf` and because people would probably forget to set/update an `fptf` key in their own module's `package.json`, setting the `fptf` key in `validate-fptf`'s package.json instead seems to be the most elegant way to do this.

You would then get the FPTF version of a module by looking directly at the version of `validate-fptf` required in the module's `dependencies` or `devDependencies`.

**Comment by juliuste** [comment]
Should we mention this at some place in the docs (or, since it's language-specific, at some special JS-FPTF-module-writing-guide-like-place)?

**Comment by derhuerst** [comment]
> Should we mention this somewhere in the docs (or, since it's language-specific, at some special JS-FPTF-module-writing-guide-like-place)?

Maybe we can use the wiki for that.

pros:

- we can let people edit the language-specific pages without the issues, PR and commits "noise"

cons:

- it's somewhat detached from the git-managed part

**Comment by juliuste** [comment]
Closing in favour of the [fpti-js](https://github.com/juliuste/fpti-js) standard.
