### ISSUE TITLE
add price attribute for journey legs

### ISSUE THREAD

**Issue by juliuste** [public-transport/friendly-public-transport-format#45]
When working with data from 🇵🇱 PKP, 🇦🇹 ÖBB or 🇲🇪 ŽPCG, I encountered the issue that there was pricing information available for specific journey legs, but not for the entire (combined) journey, as long as the price for at least one leg remained unknown.

I think it makes sense to give `leg`s an optional `price` attribute as well (as in `journey`). I know that I could already implement that without adding it to FPTF since the spec doesn't forbid it, but IMHO it makes sense to standardize this since I encountered the issue multiple times. Opinions?

**Comment by juliuste** [comment]
@derhuerst ping

**Comment by derhuerst** [comment]
Fine with making it optional. Should have the same structure as `journey.price`.
