### ISSUE TITLE
`schedule` prop in journey legs

### ISSUE THREAD

**Issue by derhuerst** [public-transport/friendly-public-transport-format#5]
Right now, a leg of a `journey` is supposed to have a `schedule` id/object, which in turn has a `route` id/object, which in turn has a `line` id/object.

In the case of static transport data, this is perfectly fine, as the information is available. But when accessing journey planning APIs, the returned data often is very sparse. With the current spec, I have to create dummy `schedule`s and `route`s, just to reference the `line`.

We need to come up with a way to model both the complex GTFS-like structure, as well as the sparse API responses.

**Comment by juliuste** [comment]
Any proposals?

**Comment by juliuste** [comment]
Since we clarified that `journey.schedule` is optional and we have the ongoing discussion in #42, I'll close this issue for now. Reopen if needed.
