### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by DmitriyBobrovskiy** [public-transport/friendly-public-transport-format#66]
Hey guys, I cannot understand if this project is still alive or not?
I see a lot of issues are opened but without any changes for a long time.
I think this project is a really good initiative, but it doesn't make sense if there is no live contributors.
It would be great if main contributors tell us what's going on and if you have any plans to work on this project. If you don't have so maybe you can find people who would like to become an owner of this and who will maintain it further.
@matkoniecz @juliuste @kiliankoe @derhuerst

**Comment by derhuerst** [comment]
Hey,

> I cannot understand if this project is still alive or not?

It is alive, the project is still relevant and maintenance is intended. Nobody has dedicated time to the open issues in the past 2 years though.

> I think this project is a really good initiative, but it doesn't make sense if there is no live contributors.

I agree that we should finally finish long-running discussions (#57, #63/#61) and changes and release a new major version.

But there's also a lot of value in a stable, rarely changing spec, e.g. like [the TopoJSON spec](https://github.com/topojson/topojson-specification). Some of the Issues in this repo are still relevant and extend the spec only (e.g. #43), so we can keep them open until someone bothers to amend the spec. Do you disagree?

> It would be great if main contributors tell us what's going on and if you have any plans to work on this project.

Yes, at least I have a plan to continue with FPTF until a better alternative emerges! I'll try to spend some time in the next week to bring it up to date.

**Comment by derhuerst** [comment]
Does this answer your questions?

**Comment by DmitriyBobrovskiy** [comment]
Yep, it does, thank you!
